src/Entity/Presentation.php
<?php

namespace App\Entity;

use App\Repository\PresentationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PresentationRepository::class)
 */
class Presentation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please, upload the product image as a png or jpg image.")
     * @Assert\File(mimeTypes={ "image/png", "image/jpg", "image/jpeg" })
     */
    private $photo_path;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $deleted;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="presentations")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="presentations")
     * @ORM\JoinColumn(name="product_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $product;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhotoPath(): ?string
    {
        return $this->photo_path;
    }

    public function setPhotoPath(string $photo_path): self
    {
        $this->photo_path = $photo_path;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDeleted(): ?string
    {
        return $this->deleted;
    }

    public function setDeleted(string $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, array('label' => false ))
            ->add('category')
            ->add('cost', TextType::class, array('label' => false ))
            ->add('description', CKEditorType::class, array(
                'label' => false,
                'config' => array(
                    'uiColor' => '#ffffff',
                    'enterMode' => 'CKEDITOR.ENTER_BR',
                    //...
                ),
            ))
            ->add('image', FileType::class, array('label' => 'Image (PNG/JPG file)', 'data_class' => null))
            ->add('availability', ChoiceType::class, array(
                    'label' => false,
                    'choices'  => array(
                        'Available' => 'available',
                        'Not Available' => 'not_available',
                    ),
                ))            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use App\Repository\CategoryRepository;

/**
 * @Route("/product")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/list", name="product_index", methods={"GET"})
     */
    public function index(ProductRepository $productRepository): Response
    {
        $products = $productRepository->findBy(
            array('deleted' => 0),
            array('id' => 'ASC')
        );
        return $this->render('product/index.html.twig', [
            'products' => $products,
        ]);
    }

    /**
     * Lists all deleted product entities.
     *
     * @Route("/admin/deleted", name="product_deleted")
     * @Method("GET")
     */
    public function deletedAction(ProductRepository $productRepository)
    {
        $products = $productRepository->findBy(
            array('deleted' => 1),
            array('id' => 'ASC')
        );
        return $this->render('product/restore.html.twig', [
            'products' => $products,
        ]);
    }

    /**
     * Lists all product entities under a category.
     *
     * @Route("/category/{category}", name="product_category")
     * @Method("GET")
     */
    public function categoryAction(ProductRepository $productRepository, CategoryRepository $categoryRepository, $category)
    {
        $categoryEntity = $categoryRepository->findOneByName($category);
        $category_id = $categoryEntity->getId();
        $products = $productRepository->findByCategory($category_id);
        return $this->render('product/category.html.twig', [
            'products' => $products,
            'category' => $category,
        ]);
    }

    /**
     * Lists all product entities by availability.
     *
     * @Route("/availability/{availability}", name="product_availability")
     * @Method("GET")
     */
    public function availabilityAction($availability)
    {
        $products = $productRepository->findBy(
            array('availability' => $availability),
            array('id' => 'ASC')
        );
        return $this->render('product/index.html.twig', [
            'products' => $products,
            'availability' => $availability,
        ]);
    }

    /**
     * @Route("/new", name="product_new", methods={"GET","POST"})
     */
    public function new(Request $request, CategoryRepository $categoryRepository): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);
        $user = $this->getUser();
        $categories = $categoryRepository->findAll();

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image')->getData();
            $category = $form->get('category')->getData();
            $now = date("d-m-Y h:i:s");
            $product->setUploaded(new \DateTime($now));            
            $product->setDeleted(0);            
            $product_title = $form->get('title')->getData();
            $trimmed_title = str_replace(" ", "_", $product_title);
            $originalName = $image->getClientOriginalName();;
            $filepath = $this->getParameter('prod_img_directory')."/$category/$trimmed_title/";
            $image->move($filepath, $originalName);
            $simple_filepath = "/img/products/$category/$trimmed_title/";
            $product->setImage($simple_filepath . $originalName);
            $product->setUser($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('product_index');
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,
            'categories' => $categories,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}/{title}", name="product_show", methods={"GET"})
     */
    public function show(Product $product): Response
    {
        $deleteForm = $this->createDeleteForm($product);

        $related_products = $this->getRandomDoctrineItem('App\Entity\Product', $product->getCategory(), 3);

        return $this->render('product/show.html.twig', array(
            'product' => $product,
            'delete_form' => $deleteForm->createView(),
            'related_products' => $related_products,
        ));
        // return $this->render('product/show.html.twig', [
        //     'product' => $product,
        // ]);
    }

    /**
     * @Route("/{id}/unlink", name="product_del_photo")
     */
    public function deleteOldFile(Request $request, Product $product): Response
    {
        $formerFileName = $product->getImage();
        $old_filepath = $this->getParameter('public_directory').$formerFileName;
        var_dump($old_filepath);
        if(file_exists($old_filepath)){ unlink($old_filepath); }
        return $this->redirectToRoute('product_edit', array('id' => $product->getId(), 'del' => $old_filepath));

    }

    /**
     * @Route("/{id}/edit", name="product_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Product $product): Response
    {
        $deleteForm = $this->createDeleteForm($product);
        $editForm = $this->createForm('App\Form\ProductType', $product);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            
            $image = $editForm->get('image')->getData();
            $category = $editForm->get('category')->getData();
            $now = date("d-m-Y h:i:s");
            $product->setUploaded(new \DateTime($now));            
            $product_title = $editForm->get('title')->getData();
            $trimmed_title = str_replace(" ", "_", $product_title);
             // if (is_object($image)){
                $product_title = $editForm->get('title')->getData();
                $trimmed_title = str_replace(" ", "_", $product_title);
                $originalName = $image->getClientOriginalName();;
                $filepath = $this->getParameter('prod_img_directory')."/$category/$trimmed_title/";

                $simple_filepath = "/img/products/$category/$trimmed_title/";
                $image->move($filepath, $originalName);
                $product->setImage($simple_filepath . $originalName);
            // } else {
            //     $config->setImage($formerFileName);
            // }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('product_edit', array('id' => $product->getId()));
        }

        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'edit_form' => $editForm->createView(),
        ]);
    }

    public static function delTree($dir) {
        $files = array_diff(scandir($dir), array('.','..'));
         foreach ($files as $file) {
           (is_dir("$dir/$file")) ? delTree("$dir/$file") : unlink("$dir/$file");
         }
         return rmdir($dir);
       }
     
    /**
     * @Route("/{id}", name="product_delete", methods={"DELETE"})
     */
    public function deleteAction(Request $request, Product $product): Response
    {
        $form = $this->createDeleteForm($product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $product->setDeleted(1);
            $category = $product->getCategory();
            $trimmed_title = str_replace(" ", "_", $product->getTitle());
            $folder = $this->getParameter('prod_img_directory')."/$category/$trimmed_title";
            $this->delTree($folder);
            $em = $this->getDoctrine()->getManager();
            $em->remove($product);
            $em->flush();
        }

        return $this->redirectToRoute('product_index');        
        
        // if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
        //     $entityManager = $this->getDoctrine()->getManager();
        //     $entityManager->remove($product);
        //     $entityManager->flush();
        // }

        // return $this->redirectToRoute('product_index');
    }

    /**
     * Restores a deleted product entity.
     *
     * @Route("/admin/restore/{id}", name="product_restore")
     */
    public function restoreAction(Request $request, Product $product)
    {

        $product->setDeleted(0);
        $em = $this->getDoctrine()->getManager();
        $em->persist($product);
        $em->flush();

        return $this->redirectToRoute('product_deleted');
    }

        /**
     * Creates a form to delete a product entity.
     *
     * @param Product $product The product entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Product $product)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('product_delete', array('id' => $product->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }

        /**
     * Retrieve one random item of given class from ORM repository.
     * 
     * @param EntityManager $em    The Entity Manager instance to use
     * @param string        $class The class name to retrieve items from
     * @return object
     */ 
    function getRandomDoctrineItem($class, $like, $limit)
    {
        $em = $this->getDoctrine()->getManager();
        static $counters = [];
        if (!isset($counters[$class])) {
            $counters[$class] = (int) $em->createQuery(
                'SELECT COUNT(c) FROM '. $class .' c' 

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/product/author.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <!-- DataTables CSS -->
    <link href="{{ asset('vendor/datatables-plugins/dataTables.bootstrap.css') }}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
{% endblock %}
{% block carousel %}{% endblock %}
{% block body %}
  <!--Main layout-->
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

    <h3>Author: {{author}}</h3>

    <table class="table table-striped" id="dt_tbl">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Category</th>
                <th>Cost</th>
                <th>Description</th>
                <th>Availability</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td><a href="{{ path('product_show', { 'id': product.id, 'title': product.title }) }}">{{ product.title }}</a></td>
                <td>{{ product.author }}</td>
                <td>{{ product.category.name }}</td>
                <td>{{ product.cost }}</td>
                <td>{{ product.description|length > 50 ? product.description|raw|slice(0, 50) ~ '...' : product.description|raw  }}</td>
                <td>{{ product.availability }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('product_show', { 'id': product.id, 'title': product.title }) }}">View</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% if app.user and app.user.active == true %}
    <ul>
        <li>
            <a href="{{ path('product_new') }}">Create a new product</a>
        </li>
        <li>
            <a href="{{ path('product_deleted') }}">Restore Deleted Products</a>
        </li>
    </ul>
{% endif %}
</div>
</main>
{% endblock %}
{% block javascripts %}
    <!-- DataTables JavaScript -->
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
    $(document).ready(function() {
        $('#dt_tbl').DataTable({
            responsive: true,
            "pageLength": 10

        });
    });
    </script>

{% endblock %}

templates/product/availability.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <!-- DataTables CSS -->
    <link href="{{ asset('vendor/datatables-plugins/dataTables.bootstrap.css') }}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
{% endblock %}
{% block carousel %}{% endblock %}
{% block body %}
  <!--Main layout-->
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

    <h3>Availability: {{availability}}</h3>

    <table class="table table-striped" id="dt_tbl">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Category</th>
                <th>Cost</th>
                <th>Description</th>
                <th>Availability</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td><a href="{{ path('product_show', { 'id': product.id, 'title': product.title }) }}">{{ product.title }}</a></td>
                {# <td>{{ product.author }}</td> #}
                <td>{{ product.category.name }}</td>
                <td>{{ product.cost }}</td>
                <td>{{ product.description|length > 50 ? product.description|slice(0, 50) ~ '...' : product.description  }}</td>
                <td>{{ product.availability }}</td>
                <td>
                     <a class="btn btn-primary" href="{{ path('product_show', { 'id': product.id, 'title': product.title }) }}">show</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% if app.user and app.user.active == true %}
    <ul>
        <li>
            <a href="{{ path('product_new') }}">Create a new product</a>
        </li>
        <li>
            <a href="{{ path('product_deleted') }}">Restore Deleted Products</a>
        </li>
    </ul>
{% endif %}
</div>
</main>
{% endblock %}
{% block javascripts %}
    <!-- DataTables JavaScript -->
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
    $(document).ready(function() {
        $('#dt_tbl').DataTable({
            responsive: true,
            "pageLength": 10

        });
    });
    </script>

{% endblock %}

templates/product/category.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <!-- DataTables CSS -->
    <link href="{{ asset('vendor/datatables-plugins/dataTables.bootstrap.css') }}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
{% endblock %}
{% block carousel %}{% endblock %}
{% block body %}
  <!--Main layout-->
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

    <h3>Category: {{category}}</h3>

    <table class="table table-striped" id="dt_tbl">
        <thead>
            <tr>
                <th>Preview</th>
                <th>Title</th>
                <th>Category</th>
                <th>Cost</th>
                <th>Description</th>
                <th>Availability</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td><a href="{{ path('product_show', { 'id': product.id, 'title': product.title }) }}"><button class="btn btn-lg" style="background-image:url('{{asset(product.image)}}'); background-repeat: no-repeat; background-position: center; background-size: contain;"></button></a></td>
                <td><a href="{{ path('product_show', { 'id': product.id, 'title': product.title }) }}">{{ product.title }}</a></td>
                <td>{{ product.category.name }}</td>
                <td>{{ product.cost }}</td>
                <td>{{ product.description|length > 50 ? product.description|slice(0, 50) ~ '...' : product.description  }}</td>
                <td>{{ product.availability }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('product_show', { 'id': product.id, 'title': product.title }) }}">View</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% if app.user and app.user.active == true %}
    <ul>
        <li>
            <a href="{{ path('product_new') }}">Create a new product</a>
        </li>
        <li>
            <a href="{{ path('product_deleted') }}">Restore Deleted Products</a>
        </li>
    </ul>
{% endif %}
</div>
</main>
{% endblock %}
{% block javascripts %}
    <!-- DataTables JavaScript -->
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
    $(document).ready(function() {
        $('#dt_tbl').DataTable({
            responsive: true,
            "pageLength": 10

        });
    });
    </script>

{% endblock %}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}
{% block carousel %}{% endblock %}
{% block body %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

    <h4>Edit {{product.title}} </h4>
    <!--Grid row-->
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-md-6 mb-4">

          {{ form_start(edit_form, {'attr': {'class': 'login-form'}}) }}
            <p class="login-img"><i class="arrow_carrot-right_alt "></i></p>
            <div class="form-group">
              <label>Product Title</label>
              {{ form_row(edit_form.title, {'attr': {'class': 'form-control', 'placeholder': 'Product Title' }}) }}
            </div>
            {# <div class="form-group">
              <label>Product Author</label>
              {{ form_row(edit_form.author, {'attr': {'class': 'form-control', 'placeholder': 'Product Author' }}) }}
            </div> #}
            <div class="form-group">
              {{ form_row(edit_form.category, {'attr': {'class': 'form-control', 'placeholder': 'Category' }}) }}
            </div>
            <div class="form-group">
              <label>Cost</label>
              {{ form_row(edit_form.cost, {'attr': {'class': 'form-control', 'placeholder': 'Cost' }}) }}
            </div>
            <div class="form-group">
              <label>Description</label>
              {{ form_row(edit_form.description, {'attr': {'class': 'form-control', 'placeholder': 'Description' }}) }}
            </div>
            <div class="form-group">
              <label>Availability</label>
              {{ form_row(edit_form.availability, {'attr': {'class': 'form-control', 'placeholder': 'Availability' }}) }}
            </div>
            <input type="hidden" id="old_title" name="old_title" value="{{product.title}}" />
            {# {{dump(product.title)}} #}
            <div class="form-group">
              {{ form_row(edit_form.image, {'attr': {'class': 'form-control' }}) }}
            </div>
            <button class="btn btn-primary btn-lg btn-block" type="submit">Edit Product</button>
          {{ form_end(edit_form) }}
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <h4>Image: </h4>
            <img style="max-height:300px;" src="{{asset(product.image)}}" />
        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
      </div>
    </main>

    <ul>
        <li>
            <a href="{{ path('product_index') }}">Back to the list</a>
        </li>
        <li>
            <a href="{{ path('product_del_photo', {'id': product.id}) }}">Delete photo</a>
        </li>
    </ul>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
  <link rel="stylesheet" href="{{asset('lightbox/dist/css/lightbox.min.css')}}">
{% endblock %}
{% block carousel %}{% endblock %}

{% block body %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
        <a href="{{ product.presentations|length > 0 ? asset(product.presentations|last.photoPath ) : '#'  }} " data-lightbox="example-set" data-title="Click the right half of the image to move forward.">
          <img  src="{{ asset(product.image) }}" class="img-fluid" style="max-height:350px;" alt="">
        </a>

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="{{path('product_category', {'category': product.category.name })}}">
                <span class="badge purple mr-1">{{product.category.name|capitalize}}</span>
              </a>
              <a href="{{path('product_availability', {'availability': product.availability })}}">
                {% set availability = product.availability|replace({"_": " "})|capitalize %}
                <span class="badge red mr-1">{{availability}}</span>
              </a>
              <a href="{{ asset(product.image )}}" data-lightbox="example-set" data-title="Click the right half of the image to move forward.">
                <span class="badge green mr-1">Preview</span>
              </a>
            </div>

            <p class="lead">
              <span>Kshs {{product.cost|number_format}}</span>
            </p>

            <p class="lead font-weight-bold">{{product.title|title}}</p>

            <p>{{product.description|raw|nl2br}}</p>

            <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input id="order_qty" type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              {% if product.id in my_cookies %}
                <button id="added_to_cart" class="btn btn-success btn-md my-0 p" type="button">Added to cart
                  <i class="fa fa-shopping-cart ml-1"></i>
                </button>
                <a id="proceed" class="btn btn-success btn-md my-0 p" href="{{path('cart')}}">CheckOut
                  <i class="fa fa-shopping-cart ml-1"></i>
                </a>
              {% else %}
                <button id="add_to_cart" class="btn btn-primary btn-md my-0 p" type="button">Add to cart
                  <i class="fa fa-shopping-cart ml-1"></i>
                </button>
                <span id="more_html"></span>
              {% endif %}
            </form>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Related Products</h4>

          <p>There are more products that are under the {{product.category.name}} category. You will find them
            very helpful. </p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        {% for product in related_products %}
            <!--Grid column-->
            <div class="col-lg-4 col-md-12 mb-4">

              <a href="{{path('product_show', {'id': product.id, 'title': product.title} )}}"><img src="{{asset(product.image)}}" class="img-fluid" style="max-height:300px; cursor:pointer" alt="{{product.title}}"></a>

            </div>
            <!--Grid column-->
        {% endfor %}

      </div>
      <!--Grid row-->
      {% if app.user and app.user.active == true %}
          <ul>
              <li>
                  <a href="{{ path('product_index') }}">Back to the list</a>
              </li>
              <li>
                  <a href="{{ path('product_edit', { 'id': product.id }) }}">Edit</a>
              </li>
              <li>
                  {{ form_start(delete_form) }}
                      <input type="submit" value="Delete">
                  {{ form_end(delete_form) }}
              </li>
          </ul>
      {% endif %}
      {# presentation photos #}
      {% for presentation in product.presentations %}
        <a style="display: none;" href="{{asset(presentation.photoPath)}}" data-lightbox="example-set" data-title="{{presentation.description}}."><img class="example-image" src="{{asset(presentation.photoPath)}}" alt="" /></a>
      {% endfor %}
    </div>
  </main>
  <!--Main layout-->


{% endblock %}
{% block javascripts %}
  <script src="{{asset('lightbox/dist/js/lightbox-plus-jquery.min.js')}}"></script>
  <script>
    $(document).on('click', '#add_to_cart', function(){
      var product_id = "{{product.id}}";
      var user_id = 2;
      var initial_cart_count = $("#cart_count").text();
      var order_qty = $("#order_qty").val();
      var new_cart_count = parseInt(initial_cart_count) + 1;
      $("#cart_count").text(new_cart_count);
      $.ajax({
          url:'{{ (path('add_to_cart')) }}',
          type: "POST",
          dataType: "json",
          data: {
            "product_id": product_id,
            "user_id": user_id,
            "order_qty": order_qty,
          },
          async: true,
          success: function (data)
          {
            console.log(data);
            $('#add_to_cart').html('Added to cart').removeClass('btn-primary').addClass('btn-success');
            var html = '<a id="proceed" class="btn btn-success btn-md my-0 p" href="{{path("cart")}}">CheckOut <i class="fa fa-shopping-cart ml-1"></i></a>';
            $('#more_html').html(html);
          },
          error: function (xhr, status, error) {
            console.log('error');
            $('#add_to_cart').html('Added to cart').removeClass('btn-primary').addClass('btn-success');
            var html = '<a id="proceed" class="btn btn-success btn-md my-0 p" href="{{path("cart")}}">CheckOut <i class="fa fa-shopping-cart ml-1"></i></a>';
            $('#more_html').html(html);
          }
      });

    });
  </script>
{% endblock %}